language: node_js

os: linux

jobs:
  include:
    - name: 'Automated API tests using Postman CLI'
      arch: amd64
      os: linux
      dist: focal
      node_js:
        - 17
      script:
        # Install Postman CLI
        - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
        # Login using your Postman API Key
        - postman login --with-api-key $POSTMAN_API_KEY
        # Run your collections using Postman CLI
        - postman collection run "30444034-49e75b9e-8f98-4a2b-9dbe-6e83ad94fb47" -e "30444034-f7123d06-4079-4f85-b8da-85b1de28519a" --integration-id "163100-${TRAVIS_BUILD_ID}"
